postgres:
  image: postgres
  environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=0103
targsofttesttask:
  image: targsofttesttask:latest
  links:
    - postgres
  environment:
    - POSTGRES_HOST=postgres
    - POSTGRES_PORT=5432